// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
window.wailsbindings = {"main":{"MySQLRepository":{"AddCount":{"name":"main.MySQLRepository.AddCount","inputs":[{"type":"main.Date"}],"outputs":[{"type":"error"}]},"AddCountFromJSON":{"name":"main.MySQLRepository.AddCountFromJSON","inputs":[{"type":"[]uint8"}],"outputs":[{"type":"error"}]},"AddDate":{"name":"main.MySQLRepository.AddDate","inputs":[{"type":"main.Date"}],"outputs":[{"type":"error"}]},"AddHabit":{"name":"main.MySQLRepository.AddHabit","inputs":[{"type":"main.Habit"}],"outputs":[{"type":"error"}]},"AddHabitFromJSON":{"name":"main.MySQLRepository.AddHabitFromJSON","inputs":[{"type":"[]uint8"}],"outputs":[{"type":"error"}]},"DeleteHabit":{"name":"main.MySQLRepository.DeleteHabit","inputs":[{"type":"uint"}],"outputs":[{"type":"bool"}]},"EditHabit":{"name":"main.MySQLRepository.EditHabit","inputs":[{"type":"main.Habit"}],"outputs":[{"type":"error"}]},"EditHabitFromJSON":{"name":"main.MySQLRepository.EditHabitFromJSON","inputs":[{"type":"[]uint8"}],"outputs":[{"type":"error"}]},"GetAllDates":{"name":"main.MySQLRepository.GetAllDates","inputs":[{"type":"uint"}],"outputs":[{"type":"[]main.Date"}]},"GetAllHabits":{"name":"main.MySQLRepository.GetAllHabits","outputs":[{"type":"[]main.Habit"}]},"GetHabit":{"name":"main.MySQLRepository.GetHabit","inputs":[{"type":"uint"}],"outputs":[{"type":"main.Habit"}]},"GetTodaysCountForHabit":{"name":"main.MySQLRepository.GetTodaysCountForHabit","inputs":[{"type":"uint"}],"outputs":[{"type":"main.Date"}]},"TodayExists":{"name":"main.MySQLRepository.TodayExists","inputs":[{"type":"uint"}],"outputs":[{"type":"bool"}]}}}};
const go = {
  "main": {
    "MySQLRepository": {
      /**
       * AddCount
       * @param {Date} arg1 - Go Type: main.Date
       * @returns {Promise<Error>}  - Go Type: error
       */
      "AddCount": (arg1) => {
        return window.go.main.MySQLRepository.AddCount(arg1);
      },
      /**
       * AddCountFromJSON
       * @param {Array<number>} arg1 - Go Type: []uint8
       * @returns {Promise<Error>}  - Go Type: error
       */
      "AddCountFromJSON": (arg1) => {
        return window.go.main.MySQLRepository.AddCountFromJSON(arg1);
      },
      /**
       * AddDate
       * @param {Date} arg1 - Go Type: main.Date
       * @returns {Promise<Error>}  - Go Type: error
       */
      "AddDate": (arg1) => {
        return window.go.main.MySQLRepository.AddDate(arg1);
      },
      /**
       * AddHabit
       * @param {Habit} arg1 - Go Type: main.Habit
       * @returns {Promise<Error>}  - Go Type: error
       */
      "AddHabit": (arg1) => {
        return window.go.main.MySQLRepository.AddHabit(arg1);
      },
      /**
       * AddHabitFromJSON
       * @param {Array<number>} arg1 - Go Type: []uint8
       * @returns {Promise<Error>}  - Go Type: error
       */
      "AddHabitFromJSON": (arg1) => {
        return window.go.main.MySQLRepository.AddHabitFromJSON(arg1);
      },
      /**
       * DeleteHabit
       * @param {number} arg1 - Go Type: uint
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "DeleteHabit": (arg1) => {
        return window.go.main.MySQLRepository.DeleteHabit(arg1);
      },
      /**
       * EditHabit
       * @param {Habit} arg1 - Go Type: main.Habit
       * @returns {Promise<Error>}  - Go Type: error
       */
      "EditHabit": (arg1) => {
        return window.go.main.MySQLRepository.EditHabit(arg1);
      },
      /**
       * EditHabitFromJSON
       * @param {Array<number>} arg1 - Go Type: []uint8
       * @returns {Promise<Error>}  - Go Type: error
       */
      "EditHabitFromJSON": (arg1) => {
        return window.go.main.MySQLRepository.EditHabitFromJSON(arg1);
      },
      /**
       * GetAllDates
       * @param {number} arg1 - Go Type: uint
       * @returns {Promise<Array<Date>>}  - Go Type: []main.Date
       */
      "GetAllDates": (arg1) => {
        return window.go.main.MySQLRepository.GetAllDates(arg1);
      },
      /**
       * GetAllHabits
       * @returns {Promise<Array<Habit>>}  - Go Type: []main.Habit
       */
      "GetAllHabits": () => {
        return window.go.main.MySQLRepository.GetAllHabits();
      },
      /**
       * GetHabit
       * @param {number} arg1 - Go Type: uint
       * @returns {Promise<Habit>}  - Go Type: main.Habit
       */
      "GetHabit": (arg1) => {
        return window.go.main.MySQLRepository.GetHabit(arg1);
      },
      /**
       * GetTodaysCountForHabit
       * @param {number} arg1 - Go Type: uint
       * @returns {Promise<Date>}  - Go Type: main.Date
       */
      "GetTodaysCountForHabit": (arg1) => {
        return window.go.main.MySQLRepository.GetTodaysCountForHabit(arg1);
      },
      /**
       * TodayExists
       * @param {number} arg1 - Go Type: uint
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "TodayExists": (arg1) => {
        return window.go.main.MySQLRepository.TodayExists(arg1);
      },
    },
  },

};
export default go;
